### ISSUE TITLE
Missing subtitle in m4b

### ISSUE THREAD

**Issue by MartinCa** [Neurrone/beets-audible#10]
It seems that `subtitle` is not filled in m4b file in my testing:
![image](https://user-images.githubusercontent.com/2415208/161055899-c9048b17-17ff-43f3-a6ee-3756024ab299.png)

I have verified with print statements that the plugin fetches the subtitle correctly from Audnexus.

Is it perhaps beets not writing the tag as expected?

**Comment by Neurrone** [comment]
Yes, I forgot to fill in the m4b tags.

There isn't an appropriate m4b tag for me to put subtitle into, I'm looking at [the list of M4b tags on this page](https://mutagen.readthedocs.io/en/latest/api/mp4.html).

Do you happen to know how the subtitle should be tagged for M4b files?

/CC @seanap do you happen to know?

**Comment by Neurrone** [comment]
I figured out how to add the subtitle tag. Let me know if this doesn't work as expected.

**Comment by MartinCa** [comment]
I just verified it with the same book as before and it is tagged with subtitle now. Thanks!
