### ISSUE TITLE
Support windows cmd cli

### ISSUE THREAD

**Issue by seanap** [Neurrone/beets-audible#11]
I have a lot of old windows pc's that I use as htpc's, so I wrote a quick script that uses putty to ssh to my Linux box, it execs into the beets container, and starts the audible plug-in. It works great and is super convenient since that .bat file lives on my nas I can double click it from any pc and instantly be tagging books.

The interface gets wonky though. Colors and special characters don't display right.  Is there any way to normalize the output so it can be easier to tag from my laptop?

I'll have to try powershell, or maybe another type of shell to see if anything else works a bit better, just wondering what is possible.

Here is a sample output:
![download_20220406_120302.jpg](https://user-images.githubusercontent.com/17012946/162018122-5a21067f-9e37-4a15-95ae-dd173dbe9d29.jpg)

**Comment by Neurrone** [comment]
See beetbox/beets#2766. I'm on Windows as well, and I believe using Windows Terminal should address this, let me know if it doesn't.

Closing because this is a known Beets issue, and out of scope for the plugin.

**Comment by seanap** [comment]
That's exactly the issue, thanks! 

In case anyone else happens to stumble across this here's how I was able to fix in Windows 10 cmd.exe using the solution found here https://superuser.com/questions/413073/windows-console-with-ansi-colors-handling:

1. Open Powershell with admin rights (Right click `Run as Administrator`)
2. `Set-ItemProperty HKCU:\Console VirtualTerminalLevel -Type DWORD 1`
