### ISSUE TITLE
Support multiple candidates

### ISSUE THREAD

**Issue by SenorSmartyPants** [Neurrone/beets-audible#19]
When searching for "Leviathan Wakes" audible returns 2 results, but only one is an option in beets-audible

[audible products results](https://api.audible.com/1.0/catalog/products/?response_groups=contributors%2Cproduct_attrs%2Cproduct_desc%2Cproduct_extended_attrs%2Cseries&num_results=10&products_sort_by=Relevance&keywords=Leviathan+Wakes+James+S.+A.+Corey)

And it seems like beets-audible is merging the dictionaries for these books. The second book is selected `B073H9PF2D` but the subtitle from the first `B00P9XDQFY` is saved to the metadata.

**Comment by Neurrone** [comment]
I suspect this is an instance of beetbox/beets#4299

**Comment by SenorSmartyPants** [comment]
I just confirmed that I have nightly installed ( I checked for your changes to beets in the PR above) and I still only get 1 candidate.

**Comment by SenorSmartyPants** [comment]
Your fix is only half way there. The change you made in 4299 stops the matches from being marked as duplicates, but then they are all added to the results dictionary using the same key, album_id which is none. This is why only the last worst match is being presented to the user.

https://github.com/beetbox/beets/blob/988bf2672cac36fb625e0fc87983ff641a0c214e/beets/autotag/match.py#L385-L386

**Comment by Neurrone** [comment]
Can you report this issue upstream?

**Comment by SenorSmartyPants** [comment]
This feature was added in #23
