### ISSUE TITLE
Data clean up/extra tags

### ISSUE THREAD

**Issue by SenorSmartyPants** [Neurrone/beets-audible#2]
There are some ID3 tags being set with 0 values, according to my inspection with Picard.

- BPM 
- Disc Number
- Total Discs

Disc values should be 1, if included at all. BPM should not be written.

Compilation flag is being set to 0. It doesn't need to be included if false
https://id3.org/iTunes%20Compilation%20Flag

Grouping field: the book should be capitalized (that's how seanap had it) -> Book # 1

Would it be possible to remove `, Book #X` from book titles if present?

I'm not sure if this data is available, but could Date, or Original Release Date, be the date the original source print book was released? So 1997 for Harry Potter and Sorcerer's Stone.

![image](https://user-images.githubusercontent.com/991618/159572748-1888442f-70e6-4233-a3a0-891aa428aad9.png)

**Comment by SenorSmartyPants** [comment]
> > Grouping field: the book should be capitalized (that's how seanap had it) -> Book # 1
> 
> Thank you, I've just pushed a fix.
Thanks!
> 
> > Would it be possible to remove , Book #X from book titles if present?
> 
> Could you provide an example of what you'd want it to be instead if a title is present?

https://www.audible.com/pd/Harry-Potter-and-the-Sorcerers-Stone-Book-1-Audiobook/B017V4IM1G

I would like the title saved into tags to be `Harry Potter and the Sorcerer's Stone`

**Comment by SenorSmartyPants** [comment]
I was able to remove the BPM tag by adding a line to on_write
```
    def on_write(self, item, path, tags):
        tags["itunes_media_type"] = "Audiobook"
        # Strip unwanted tags that Beets automatically adds
        tags['mb_trackid'] = None
        tags['lyrics'] = None
        tags['bpm'] = None
```

**Comment by Neurrone** [comment]
I believe all the tag issues reported here have been fixed. Closing as completed.
