### ISSUE TITLE
Enable discussions on github for sharing of beets config files, etc

### ISSUE THREAD

**Issue by SenorSmartyPants** [Neurrone/beets-audible#28]
I'd like a way to share and talk about different configurations for beets with this plugin. I've made tweaks to path templates and filenaming in my set up that others may find interesting.

**Comment by Neurrone** [comment]
I've just enabled it, see https://github.com/Neurrone/beets-audible/discussions

**Comment by SenorSmartyPants** [comment]
Thanks
