### ISSUE TITLE
Missing series fields

### ISSUE THREAD

**Issue by SenorSmartyPants** [Neurrone/beets-audible#3]
Some series fields are missing in my testing.

Missing from MP3
- Show Work & Movement

Missing from M4B
- Album Sort Order
- Movement
- Movement Number
- Series
- SeriesPosition
- Show Work & Movement

The only series field present in M4B is `grouping`

https://www.audible.com/pd/Leviathan-Wakes-Audiobook/B073H9PF2D

![image](https://user-images.githubusercontent.com/991618/159772639-d9f7d16e-2410-4a42-92cf-0b88e1777f2b.png)

**Comment by Neurrone** [comment]
Thanks for the bug report. Let me investigate, I remember seeing some of these fields do get added to the mp3s I've tested, so I'm not sure what's going on there.

**Comment by Neurrone** [comment]
For MP3, `MVIN` is already set. If by show work you mean `shwm`, that should only be applicable for m4b files.

For M4b, I've just pushed an update that adds `mvn` (series name) and `soal` (album sort). I'm not able to add the series position under `mvi` as not all values can be converted to integers per the tag requirements (e.g, "1-3" for a multi-book m4b) which causes a runtime error if attempting to write such invalid data.

I'll add shwm for M4b the next time I work on this.

@seanap how does Mp3tag add series position to m4b files? Does it use custom tags?

**Comment by SenorSmartyPants** [comment]
You could test that `mvi` is an integer and then add the field. I would imagine more will be integers than not.

**Comment by seanap** [comment]
@Neurrone The movement (mvin) and movementname (mvnm) are built into id3v2.3+.  I had also added two custom tags (series and series-part) just incase something ever looked at them.  I don't think anything looks for the series in movement or custome series tags.  Prologue was trying to use TIT1 Content Group, but that is a singular tag and doesn't have a separate series position component.

Form the mp3tag tag filed mappings page:
![image](https://user-images.githubusercontent.com/17012946/161438584-f978539b-9277-4c50-b36c-06cec16151fd.png)

**Comment by SenorSmartyPants** [comment]
> I had also added two custom tags (series and series-part) just incase something ever looked at them.

Audiobookserver is looking at these fields now.

https://www.audiobookshelf.org/docs/#metadata

**Comment by Neurrone** [comment]
I've added the following tags to m4b files:

* `mvi` (on a best effort basis)
* `pgap`
* `shwm`
* `stik`

This should fix all the missing tags for m4b files.

**Comment by Neurrone** [comment]
I've also updated mp3 files to use `txx_series-part` instead of `seriesposition` to match audiobookshelf. 

This should be all the missing tags. Let me know if I've missed out anything.

**Comment by SenorSmartyPants** [comment]
Series and Series-part are missing from M4Bs.

But everything else seems there.

**Comment by Neurrone** [comment]
Ah, I wasn't sure how to add those tags to m4b files, I'll reopen this.

**Comment by Neurrone** [comment]
The missing Series and Series-part tags were added in #18.
