### ISSUE TITLE
Disable musicbrainz

### ISSUE THREAD

**Issue by buswedg** [Neurrone/beets-audible#38]
Seems beets v1.6 (possibly earlier versions too) allow a config.yaml setting to disable musicbrainz via the below. So you don't need to ping a dead host. May want to do some testing and update the audible plugin config/ readme accordingly.

`
musicbrainz:
  enabled: no
`

**Comment by Neurrone** [comment]
It doesn't seem to be in v1.6 yet, see https://github.com/Neurrone/beets-audible/pull/33#issuecomment-1284736072

**Comment by buswedg** [comment]
hmm strange. I'm on the latest linuxserver image which I believe is running 1.6, and made the change above which has suppressed the musicbrainz timeout warnings I was getting previously.

**Comment by buswedg** [comment]
> hmm strange. I'm on the latest linuxserver image which I believe is running 1.6, and made the change above which has suppressed the musicbrainz timeout warnings I was getting previously.

yeh, confirmed.

```
beets version 1.6.0
Python version 3.9.15
```

using a custom docker-compose via lscr.io/linuxserver/beets:latest.

not a big deal, looks like the change is coming 'officially' soon anyway.

**Comment by Neurrone** [comment]
Addressed by merging #33
