### ISSUE TITLE
.nfo files along with metadata.yml

### ISSUE THREAD

**Issue by jakeau** [Neurrone/beets-audible#45]
G'day, 

Alot of audiobooks use .nfo files, it would be really awesome if they could be read as well as .yml

Example of an .nfo

General Information
===================
 Title:                  Uncanny Collateral: Valkyrie Collections, Book 1
 Author:                 Brian McClellan
 Read By:                Luke Daniels
 Copyright:              2019
 Audiobook Copyright:    2019
 Genre:                  Fantasy
 Publisher:              Brian McClellan
 Duration:               5 hours, 10 minutes, 35 seconds
 Chapters:               18

Media Information
=================
 Source Format:          Audible AAX
 Source Sample Rate:     22050 Hz
 Source Channels:        2
 Source Bitrate:         63 kbits

 Lossless Encode:        No
 Encoded Codec:          LAME MP3
 Encoded Sample Rate:    22050 Hz
 Encoded Channels:       2
 Encoded Bitrate:        64 kbits

 Ripper:                 inAudible 1.97

Book Description
================
Alek Fitz is a reaper, a collection agent who works for the supernatural elements of the world, tracking down debtors and solving problems for clients as diverse as the Lords of Hell, vampires, Haitian loa, and goblins. He’s even worked for the Tooth Fairy on occasion. Based out of Cleveland, Ohio, Alek is the best in the game. As a literal slave to his job, he doesn’t have a choice.

**Comment by Neurrone** [comment]
I'm not comfortable with doing so, as .nfo files are typically only seen in warez / pirated content.
