### ISSUE TITLE
Error after install, before import

### ISSUE THREAD

**Issue by potter-jason** [Neurrone/beets-audible#46]
Hello
Im getting an error when running beet --version, so i checked the logs and am showing the below. Did I miss something in the install? Did the docker option, running in ubuntu22.04, latest version of docker compose. 

** error loading plugin audible:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
ModuleNotFoundError: No module named 'beetsplug.audible'
** error loading plugin copyartifacts:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
ModuleNotFoundError: No module named 'beetsplug.copyartifacts'
error: unknown command 'web'
** error loading plugin audible:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
ModuleNotFoundError: No module named 'beetsplug.audible'

**Comment by Neurrone** [comment]
It looks like the plugins weren't installed properly. What did you do to install it?

**Comment by grtembey** [comment]
I had the same issue. Looks like something broke in the latest release of beets.

Rolling back to an older beets image solved it for me. Here is the image I used: lscr.io/linuxserver/beets:1.6.0-ls149

**Comment by gazpachoking** [comment]
Looks like the latest beets image doesn't include a pip executable. You can fix it by changing 'pip' in the install script to 'python -m pip'

**Comment by Neurrone** [comment]
Closing this to clean up old issues. Let me know if this is still relevant.
