### ISSUE TITLE
Not finding audiobooks unless i search for author and book name

### ISSUE THREAD

**Issue by StefanDorschu** [Neurrone/beets-audible#47]
I'm happily using the plugin but in general it does not find the correct audiobooks unless i search for (command E) author and book name.

As i am from germany i am trying to tag german audio books. Maybe this is the reason? Is there a way to optimize it?

**Comment by HabelStefan** [comment]
Thanks for your quick reply.

Is there a way to make the search more flexible? See my example in the attached image.

<img width="1138" alt="Example" src="https://user-images.githubusercontent.com/24601959/223089182-fab3a596-48bf-4de4-9ff3-d5fef3391e58.png">

**Comment by Neurrone** [comment]
Probably not, because the order that results are given is the same as the order of results when you use the search box on the Audible website.

**Comment by Neurrone** [comment]
Support for non-US regions has been released with v1.0 of Beets-audible, which includes the changes from #67.

See the [Changelog](https://github.com/Neurrone/beets-audible/blob/main/CHANGELOG.md) for the list of changes.
