### ISSUE TITLE
Audible Plugin Not loading

### ISSUE THREAD

**Issue by Doug411** [Neurrone/beets-audible#51]
My audible plugin is not loading.  Im running on a raspberry pi (Arm64).   I tried a verbose import and it seems my plugin path is empty.  I tried changing the location of my scripts based on a post I read in this discussion board, but that didnt seem to solve the issue.

root@5474aacfeb61:/# beet --version
beets version 1.6.0
Python version 3.10.11
plugins: chroma, convert, embedart, fetchart, lastgenre, replaygain, scrub, web

root@5474aacfeb61:/# beet -v import /untagged
user configuration: /config/config.yaml
data directory: /config
plugin paths: 
Sending event: pluginload
library database: /config/musiclibrary.blb
library directory: /music
Sending event: library_opened
Sending event: import_begin
state file could not be read: [Errno 2] No such file or directory: '/config/state.pickle'
state file could not be read: [Errno 2] No such file or directory: '/config/state.pickle'
Sending event: import_task_created
Sending event: import_task_start
Looking up: /untagged/AnimalFarm
Tagging  - 
No album ID found.
Search terms:  - 
Album might be VA: True
chroma: acoustid album candidates: 0
Evaluating 0 candidates.

/untagged/AnimalFarm (1 items)
Sending event: import_task_before_choice
Sending event: before_choose_candidate
No matching release found for 1 tracks.
For help, see: https://beets.readthedocs.org/en/latest/faq.html#nomatch
[S]kip, Use as-is, as Tracks, Group albums, Enter search, enter Id, aBort? S
Sending event: import_task_choice
state file could not be read: [Errno 2] No such file or directory: '/config/state.pickle'
Sending event: import
Sending event: cli_exit
root@5474aacfeb61:/# 

**docker compose**
version: "3"
services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      # Update as needed
      - PUID=1000
      - PGID=1001
      - TZ=America/US
    volumes:
      - ./config:/config
      - ./plugins:/plugins
      - ./scripts:/custom-cont-init.d
      - /media/pi/CribShare/Books/AudioBooks:/audiobooks
      - /media/pi/CribShare/Books/AudioBookUpload/untagged:/untagged
    restart: unless-stopped

**Comment by gtronset** [comment]
@Doug411 You'll need to add the plugin to the list of plugins to load from your config file. Right now you're only loading:

> plugins: chroma, convert, embedart, fetchart, lastgenre, replaygain, scrub, web

It should load once you add `audible` to the list of plugins in `/config/config.yaml`.

**Comment by Doug411** [comment]
Thanks for the response

This is my config.yaml.  Audible it there, but not loading.   I pulled the config.yaml  directly from the WIKI and just updated the Plex section (not showing my token).   MuicBrainz is doing the lookup even though I have it set to disabled, and audible isnt loading.  




# add audible to the list of plugins
# copyartifacts is optional but recommended if you're manually specifying metadata via metadata.yml, see the "Importing non-audible content" section
plugins: audible copyartifacts edit fromfilename scrub

directory: /audiobooks

# Place books in their own folders to be compatible with Booksonic and Audiobookshelf servers
paths:
  # For books that belong to a series
  "albumtype:audiobook series_name::.+ series_position::.+": $albumartist/%ifdef{series_name}/%ifdef{series_position} - $album%aunique{}/$track - $title
  "albumtype:audiobook series_name::.+": $albumartist/%ifdef{series_name}/$album%aunique{}/$track - $title
  # Stand-alone books
  "albumtype:audiobook": $albumartist/$album%aunique{}/$track - $title
  default: $albumartist/$album%aunique{}/$track - $title
  singleton: Non-Album/$artist - $title
  comp: Compilations/$album%aunique{}/$track - $title
  albumtype_soundtrack: Soundtracks/$album/$track $title

# disables musicbrainz lookup, as it doesn't help for audiobooks
musicbrainz:
  enabled: no

audible:
  # if the number of files in the book is the same as the number of chapters from Audible,
  # attempt to match each file to an audible chapter
  match_chapters: true
  source_weight: 0.0 # disable the source_weight penalty
  fetch_art: true # whether to retrieve cover art
  include_narrator_in_artists: true # include author and narrator in artist tag. Or just author
  keep_series_reference_in_title: true # set to false to remove ", Book X" from end of titles
  keep_series_reference_in_subtitle: true # set to false to remove subtitle if it contains the series name and the word book ex. "Book 1 in Great Series", "Great Series, Book 1"

  write_description_file: true # output desc.txt
  write_reader_file: true # output reader.txt

copyartifacts:
  extensions: .yml # so that metadata.yml is copied, see below

scrub:
  auto: yes # optional, enabling this is personal preference 

plex:
  host: 192.168.1.89
  port: 33300
 token: X # Your plex token

**Comment by Neurrone** [comment]
Something else to try is to look at the contents of the `.yml` file in the docker container to rule out the possibility that the config isn't being mapped correctly into the container.

**Comment by SpencerMKSmith** [comment]
This is the exact same problem I'm having..

**Comment by gtronset** [comment]
Another thing to do to help diagnose _where_ the breakdown is would be to run `pip3 list` and ensure that `beets-audible` is listed as an installed python package. If it's not listed then the installation isn't set up correctly.

**Comment by ChiSoxDev** [comment]
I have this same issue. It appears that the docker image doesn't auto-install the audible plugin, but the beets plugin page doesnt have any details on HOW to install. A manual pip install should work, but whats the proper name?

**Comment by ChiSoxDev** [comment]
@Doug411 Every re-creation of the container clears the manually installed plugings as well. It does not appear to be storing them in the /plugins directory mapped as a volume. So what is the correct way to install the plugins when using a docker container?

**Comment by ChiSoxDev** [comment]
@Doug411 I believe I have this issue figured out. If I'm correct, you are using seanap's branch off of this instead of the original? I was. There are two issues related to seanap's config which need to be addressed. I will create an issue over there as well.

First:
The mapping of the scripts directory is incorrect in Seanap's compose.
It should be: ./scripts:/custom-cont-init.d
not: ./scripts:/config/custom-cont-init.d

Second:
Seanap's guide doesn't include a very important step from this github.
![image](https://github.com/Neurrone/beets-audible/assets/121800704/8b504727-8d3b-4aca-8b0c-ed5d6fdae7cc)

If you fix the mapping of the scripts directory, then add in your plugins properly like this says. Everything works!

@gtronset you can probably mark this resolved now if they confirm.
@Doug411 and @SpencerMKSmith  give this a try.

**Comment by Neurrone** [comment]
Closing this to clean up old issues. This also seems to be caused by using the fork.
