### ISSUE TITLE
Untagged and Tagged files disappear after import

### ISSUE THREAD

**Issue by Doug411** [Neurrone/beets-audible#52]
When I run a beet import, the console finds the tags, and appears to process successfully.  However, it doesnt move the tagged files to my library.  Additionally, it empties out the import folder.

Also, if I skip a file in the import folder during import, is there a way to reprocess later?  I dont see it listed in the DB when I execute a beet list command.  In the example below, it shows beets skipping previously imported "animal farm", however that isnt in the database (I'm pretty sure I skipped during import, because no tags were found).   Note:   The entries for Time Machine are in the database, but the files were not copied to my Library, and the original files are gone.  That is the primary issue.

FYI running docker on raspberry pi 4 with 64 bit kernal.

root@5474aacfeb61:/# beet list
H. G. Wells read by Mark Nelson - The Time Machine - Chapter 1
H. G. Wells read by Mark Nelson - The Time Machine - Chapter 2
H. G. Wells read by Mark Nelson - The Time Machine - Chapter 3
H. G. Wells read by Mark Nelson - The Time Machine - Chapter 4
H. G. Wells read by Mark Nelson - The Time Machine - Chapter 5
H. G. Wells read by Mark Nelson - The Time Machine - Chapter 6
H. G. Wells read by Mark Nelson - The Time Machine - Chapter 7
H. G. Wells read by Mark Nelson - The Time Machine - Chapter 8
H. G. Wells read by Mark Nelson - The Time Machine - Chapter 9
H. G. Wells read by Mark Nelson - The Time Machine - Chapter 10
H. G. Wells read by Mark Nelson - The Time Machine - Chapter 11
H. G. Wells read by Mark Nelson - The Time Machine - Chapter 12
root@5474aacfeb61:/# beet -v import /untagged
user configuration: /config/config.yaml
data directory: /config
plugin paths: 
Sending event: pluginload
library database: /config/musiclibrary.blb
library directory: /music
Sending event: library_opened
Sending event: import_begin
Skipping previously-imported path: /untagged/AnimalFarm
No files imported from /untagged
Skipped 1 paths.
Sending event: import
Sending event: cli_exit

**Comment by Cluedo97** [comment]
yep same problem for me, everything just deleted. Really new to all of this and should have made more backups but now almost all of the files are gone.

**Comment by Neurrone** [comment]
Regarding processing of folders that have been processed before, there is a `-I` option for the `beet import` command that reprocesses already imported directory. Use `beet import --help` for more info.

I'd need a verbose log when the files disappear to figure out what's going on.

**Comment by Neurrone** [comment]
Closing this to clean up old issues. Let me know if this is still relevant.
