### ISSUE TITLE
Add the ability to retrieve metadata from different regions using the Audnex API when importing audiobooks.

### ISSUE THREAD

**Issue by sunrize** [Neurrone/beets-audible#66]
1. I'm using the Audnex API, so I'm limited by the results that they return. I don't think they support searches for other countries as far as I'm aware, so that's something that I don't have control over unfortunately
2. I don't get what you mean by this, could you elaborate?

_Originally posted by @Neurrone in https://github.com/Neurrone/beets-audible/issues/50#issuecomment-1697716131_
            
Audnex API supports `region` [query parameter](https://audnex.us/#tag/Books/operation/getBookById). I would like the option to choose the region for metadata when importing audiobooks, either on a book-by-book basis, or to have a predefined region in the plugin configuration.

**Comment by Neurrone** [comment]
This feature has been released with v1.0 of Beets-audible, which includes the changes from #67.

See the [Changelog](https://github.com/Neurrone/beets-audible/blob/main/CHANGELOG.md) for the list of changes.
